version: '3.8'

services:
    web:
        build:
            context: ./CrudApp
            dockerfile: Dockerfile.run
        image: venijamin/web
        container_name: web
        ports:
            - "8080:8080"
        depends_on:
            - db
            - migration
        environment:
            - DefaultConnection=${CONNECTION_STRING}
    db:
        image: postgres
        container_name: db
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        env_file: .env
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
    
    migration:
        build:
            context: ./CrudApp
            dockerfile: Dockerfile.migrations
        image: venijamin/db-migrations
        container_name: migration
        depends_on:
            - db
        environment:
            - DefaultConnection=${CONNECTION_STRING}

volumes:
    postgres-data:
