version: '3.8'

services:
    web:
        build:
            context: ./CrudApp
            dockerfile: Dockerfile
        container_name: web
        ports:
            - "8080:8080"
        command: sh /migrations.sh
        depends_on:
            - db
    db:
        image: postgres
        container_name: db
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        env_file: .env
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  postgres-data:
