FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dotnet

# Install EF Core to apply database migrations
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

WORKDIR /app
COPY . .

ENTRYPOINT [ "sh", "migrations.sh"]
