name: Build and Push App Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push App Docker image
        run: |
          docker build -t venijamin/web:latest -f ./CrudApp/Dockerfile.run ./CrudApp
          docker build -t venijamin/db-migrations:latest -f ./CrudApp/Dockerfile.migrations ./CrudApp
          docker push venijamin/web:latest
          docker push venijamin/db-migrations:latest

        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
